### ISSUE TITLE
Use Bitbucket API v2

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0-extensions/auth0-bitbucket-deploy#10]
We are currently using API v1, but v2 is available: https://blog.bitbucket.org/2013/11/12/api-2-0-new-function-and-enhanced-usability/

**Comment by navi2601** [comment]
Any timeline on updating to v2 bitbucket API as v1 is getting deprecated very soon (https://confluence.atlassian.com/bitbucket/version-1-423626337.html)?

**Comment by fyockm** [comment]
@navi2601 yes, Bitbucket API v2 is on our radar. while api v1 will be deprecated as of 30 June 2018, it will continue to be accessible through the end of December. That said, we will try to have it updated by the end of the month.

As always, the extensions are open source, so feel free to submit a PR if you are able.
