### ISSUE TITLE
Support deploying hooks

### ISSUE THREAD

**Issue by jebbench** [auth0-extensions/auth0-bitbucket-deploy#22]
We're trying (where possible) to use hooks; having to manually deploy them after a change is not a attractive solution for us.

Do you have deploying Hooks from Bitbucket on your roadmap?

**Comment by dctoon** [comment]
@jebbench by using the Bitbucket Webhooks you are able to automatically deploy when code is pushed to a repository or a PR is merged. More info can be found in the _Configure the Extension_ section on this page [page](https://auth0.com/docs/extensions/bitbucket-deploy).

**Comment by jebbench** [comment]
Yeah.. for rules and hosted pages but not for hooks afaik.

**Comment by dctoon** [comment]
Indeed, currently we don't have support for Hooks. But the [Webtask CLI](https://github.com/auth0/wt-cli#auth0-cli-extend-auth0-with-custom-code-beta) allows you to create, list, enable/disable, edit, and remove Auth0 hooks.
