### ISSUE TITLE
"no auth mechanism defined" error after update from 2.5 to 2.6

### ISSUE THREAD

**Issue by j-m-x** [auth0-extensions/auth0-bitbucket-deploy#39]
Today I noticed an update (2.6) to this extension on our Auth0 Management Dashboard and tried it on our test tenant, but it no longer works. I get a `no auth mechanism defined` on every attempt of running the deploy.

Figured I would have look and see if I can help out with a fix or get some extra info debugging. But I'm a bit confused and unsure if I am even in the right place. Latest release seems to be 2.2.4 looking at the tags and commits. But the docs make references to a 2.3 version, and I've been running version 2.5 successfully for a few weeks on my company's Auth0 instance. On top of that I noticed another repo [here](https://github.com/auth0-extensions/auth0-deploy-extensions) that seems to have to same functionality as this repo, even many overlap in code, but with the other deploy plugins combined into a single repo, it has no releases yet, but current version is set 1.1.0.

Can someone point me in the right direction?

**Comment by fyockm** [comment]
hi @j-m-x - with the 2.6 release of this extension, we have moved from separate repositories for each the deployment extensions (github, gitlab, bitbucket, and vsts) to building via a single auth0-deploy-extensions monorepo. this will make them much easier to maintain and keep track of fixes across all four extensions. this repo will be marked as read-only very soon.

@zxan1285 has fixed the error you mentioned (see https://github.com/auth0-extensions/auth0-deploy-extensions/pull/4), and the update has already been deployed as `auth0-bitbucket-deployu@2.6.2`.

[CHANGELOG](https://github.com/auth0-extensions/auth0-deploy-extensions/blob/master/CHANGELOG.md#111---2019-01-31)

**Comment by j-m-x** [comment]
Awesome and thanks a lot for the quick response and fix. 👍
